#####################################################################
2023-06-15 19:36:08.623520+09:00
카테고리는 java 로 하겠습니다.
주제는 SSE core task scheduler startup problem in eclipse 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-15 19:42:13.611457+09:00
카테고리는 java 로 하겠습니다.
주제는 flutter doctor --android-licenses not working due to java.lang.UnsupportedClassVersionError 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-15 23:30:01.998250+09:00
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.stackexchange.com', port=443): Max retries exceeded with url: /2.2/sites/?pagesize=1000&page=1&filter=%21%2AL1%2AAY-85YllAr2%29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/.local/lib/python3.10/site-packages/stackapi/stackapi.py", line 197, in fetch
    response = requests.get(base_url, params=params, proxies=self.proxy)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.stackexchange.com', port=443): Max retries exceeded with url: /2.2/sites/?pagesize=1000&page=1&filter=%21%2AL1%2AAY-85YllAr2%29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 14, in <module>
    SITE = StackAPI('stackoverflow')
  File "/home/yoon/.local/lib/python3.10/site-packages/stackapi/stackapi.py", line 72, in __init__
    sites = self.fetch('sites', filter='!*L1*AY-85YllAr2)', pagesize=1000)
  File "/home/yoon/.local/lib/python3.10/site-packages/stackapi/stackapi.py", line 199, in fetch
    raise StackAPIError(self._previous_call, str(e), str(e), str(e))
stackapi.stackapi.StackAPIError: (None, "HTTPSConnectionPool(host='api.stackexchange.com', port=443): Max retries exceeded with url: /2.2/sites/?pagesize=1000&page=1&filter=%21%2AL1%2AAY-85YllAr2%29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)'))", "HTTPSConnectionPool(host='api.stackexchange.com', port=443): Max retries exceeded with url: /2.2/sites/?pagesize=1000&page=1&filter=%21%2AL1%2AAY-85YllAr2%29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)'))", "HTTPSConnectionPool(host='api.stackexchange.com', port=443): Max retries exceeded with url: /2.2/sites/?pagesize=1000&page=1&filter=%21%2AL1%2AAY-85YllAr2%29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f595b201fc0>, 'Connection to api.stackexchange.com timed out. (connect timeout=None)'))")
#####################################################################
2023-06-15 23:37:05.464920+09:00
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 14, in <module>
    SITE = StackAPI('stackoverflow')
  File "/home/yoon/.local/lib/python3.10/site-packages/stackapi/stackapi.py", line 72, in __init__
    sites = self.fetch('sites', filter='!*L1*AY-85YllAr2)', pagesize=1000)
  File "/home/yoon/.local/lib/python3.10/site-packages/stackapi/stackapi.py", line 197, in fetch
    response = requests.get(base_url, params=params, proxies=self.proxy)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
#####################################################################
2023-06-16 03:00:01.714648+09:00
카테고리는 java 로 하겠습니다.
주제는 GraalVM (native-image) can not compile logback dependencies 로 하겠습니다.
제목 만들었습니다. "Resolving GraalVM Compilation Issues with Logback Dependencies" : 87
본문 1/2 만들었습니다. : 1229
본문 2/2 만들었습니다. : 1110
참고할만한 사이트를 만들었습니다. "Resolving GraalVM Compilation Issues with Logback Dependencies" : 427
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-17 13:00:01.400216+09:00
카테고리는 java 로 하겠습니다.
주제는 Duplicate class in Kotlin Android 로 하겠습니다.
제목 만들었습니다. Resolving Duplicate Class Error in Kotlin Android Development : 75
본문 1/2 만들었습니다. : 1015
본문 2/2 만들었습니다. : 865
참고할만한 사이트를 만들었습니다. Resolving Duplicate Class Error in Kotlin Android Development : 447
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-18 23:00:02.028772+09:00
카테고리는 java 로 하겠습니다.
주제는 Java recognizes some files and directories but still thinks they do not exist 로 하겠습니다.
제목 만들었습니다. "Resolving Java's File and Directory Recognition Errors" : 85
본문 1/2 만들었습니다. : 1194
본문 2/2 만들었습니다. : 1011
참고할만한 사이트를 만들었습니다. "Resolving Java's File and Directory Recognition Errors" : 345
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-19 05:00:01.679638+09:00
카테고리는 java 로 하겠습니다.
주제는 flutter doctor --android-licenses not working due to java.lang.UnsupportedClassVersionError 로 하겠습니다.
제목 만들었습니다. "Resolving the java.lang.UnsupportedClassVersionError in Flutter Doctor Android Licenses" : 94
본문 1/2 만들었습니다. : 966
본문 2/2 만들었습니다. : 970
참고할만한 사이트를 만들었습니다. "Resolving the java.lang.UnsupportedClassVersionError in Flutter Doctor Android Licenses" : 416
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-20 05:00:01.540720+09:00
카테고리는 java 로 하겠습니다.
주제는 Spring Boot 3 springdoc-openapi-ui doesn&#39;t work 로 하겠습니다.
제목 만들었습니다. Resolving Spring Boot 3 springdoc-openapi-ui Functionality Issues : 89
본문 1/2 만들었습니다. : 987
본문 오류발생 :  The server had an error while processing your request. Sorry about that! {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that!",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that!', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Mon, 19 Jun 2023 20:02:08 GMT', 'Content-Type': 'application/json', 'Content-Length': '176', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-model': 'gpt-4-0613', 'openai-organization': 'user-cfljr7asc24pxittu0n11pgh', 'openai-processing-ms': '47', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3000', 'x-ratelimit-limit-tokens': '250000', 'x-ratelimit-remaining-requests': '2999', 'x-ratelimit-remaining-tokens': '247270', 'x-ratelimit-reset-requests': '20ms', 'x-ratelimit-reset-tokens': '655ms', 'x-request-id': '44865eb89ba3d675544a59d8e727deb0', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7d9e5e341b44a7cc-ICN', 'alt-svc': 'h3=":443"; ma=86400'}
프로그램 종료.
#####################################################################
2023-06-20 11:00:01.986710+09:00
카테고리는 java 로 하겠습니다.
주제는 Accessing protected method of anonymous object vs by a named reference 로 하겠습니다.
제목 만들었습니다. "Understanding the Differences: Accessing Protected Methods of Anonymous Objects vs Named References" : 89
본문 1/2 만들었습니다. : 1231
본문 2/2 만들었습니다. : 1204
참고할만한 사이트를 만들었습니다. "Understanding the Differences: Accessing Protected Methods of Anonymous Objects vs Named References" : 269
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-20 19:00:01.645393+09:00
카테고리는 java 로 하겠습니다.
주제는 How downcasting takes place by using the &#39;final&#39; keyword in Java 로 하겠습니다.
제목 만들었습니다. "Understanding Downcasting in Java Using the 'Final' Keyword" : 92
본문 1/2 만들었습니다. : 1016
본문 2/2 만들었습니다. : 955
참고할만한 사이트를 만들었습니다. "Understanding Downcasting in Java Using the 'Final' Keyword" : 296
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-21 01:00:02.286534+09:00
카테고리는 java 로 하겠습니다.
주제는 @EnableGlobalMethodSecurity is deprecated in the new spring boot 3.0 로 하겠습니다.
제목 만들었습니다. "Transitioning from @EnableGlobalMethodSecurity in Spring Boot 3.0: A Comprehensive Guide" : 98
본문 1/2 만들었습니다. : 1153
본문 2/2 만들었습니다. : 969
참고할만한 사이트를 만들었습니다. "Transitioning from @EnableGlobalMethodSecurity in Spring Boot 3.0: A Comprehensive Guide" : 311
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-21 03:00:01.837066+09:00
카테고리는 java 로 하겠습니다.
주제는 I can&#39;t create a new project with java language anymore on Android Studio Flamingo? 로 하겠습니다.
제목 만들었습니다. "Resolving Java Language Project Creation Issues in Android Studio Flamingo" : 96
본문 1/2 만들었습니다. : 1009
본문 2/2 만들었습니다. : 1300
참고할만한 사이트를 만들었습니다. "Resolving Java Language Project Creation Issues in Android Studio Flamingo" : 333
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-21 23:00:01.654118+09:00
카테고리는 java 로 하겠습니다.
주제는 What is the difference between green threads and virtual threads? 로 하겠습니다.
제목 만들었습니다. "Understanding the Difference: Green Threads vs Virtual Threads" : 83
본문 1/2 만들었습니다. : 1070
본문 2/2 만들었습니다. : 1019
참고할만한 사이트를 만들었습니다. "Understanding the Difference: Green Threads vs Virtual Threads" : 250
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-22 17:00:01.815482+09:00
카테고리는 java 로 하겠습니다.
주제는 Stream.peek() can be skipped for optimization 로 하겠습니다.
제목 만들었습니다. Optimizing Stream.peek() Usage in Java : 78
본문 1/2 만들었습니다. : 1100
본문 2/2 만들었습니다. : 988
참고할만한 사이트를 만들었습니다. Optimizing Stream.peek() Usage in Java : 417
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-23 23:00:01.564888+09:00
카테고리는 java 로 하겠습니다.
주제는 Will x64 jdk-1.8 work in Mac with Apple Silicon (M1) Chip? 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-25 15:00:01.906888+09:00
카테고리는 java 로 하겠습니다.
주제는 Accessing protected method of anonymous object vs by a named reference 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-26 21:00:02.101342+09:00
카테고리는 java 로 하겠습니다.
주제는 How can I run JDK 19 with Structured Concurrency? 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-27 01:00:01.956213+09:00
카테고리는 java 로 하겠습니다.
주제는 Spring initializr project results in Unsupported class file major version 64 로 하겠습니다.
제목 만들었습니다. "Resolving the 'Unsupported Class File Major Version 64' Error in Spring Initializr Project" : 94
본문 1/2 만들었습니다. : 1038
본문 2/2 만들었습니다. : 902
참고할만한 사이트를 만들었습니다. "Resolving the 'Unsupported Class File Major Version 64' Error in Spring Initializr Project" : 244
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-27 13:00:02.327390+09:00
카테고리는 java 로 하겠습니다.
주제는 Stream.peek() can be skipped for optimization 로 하겠습니다.
제목 만들었습니다. Optimizing Java Streams: The Misuse of Stream.peek() : 82
본문 1/2 만들었습니다. : 1219
본문 2/2 만들었습니다. : 841
참고할만한 사이트를 만들었습니다. Optimizing Java Streams: The Misuse of Stream.peek() : 309
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-28 01:00:02.235179+09:00
카테고리는 java 로 하겠습니다.
주제는 How to fix Spring authorizeRequests is deprecated? 로 하겠습니다.
제목 만들었습니다. Resolving the Deprecated Spring authorizeRequests Issue : 78
본문 1/2 만들었습니다. : 1188
본문 2/2 만들었습니다. : 845
참고할만한 사이트를 만들었습니다. Resolving the Deprecated Spring authorizeRequests Issue : 257
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-28 21:00:02.260738+09:00
카테고리는 java 로 하겠습니다.
주제는 upgrade to SnakeYaml 1.31 in spring-boot-starter-parent 2.7.3 로 하겠습니다.
제목 만들었습니다. "Resolving Error through SnakeYaml 1.31 Upgrade in Spring-Boot-Starter-Parent 2.7.3" : 110
본문 1/2 만들었습니다. : 1131
본문 2/2 만들었습니다. : 974
참고할만한 사이트를 만들었습니다. "Resolving Error through SnakeYaml 1.31 Upgrade in Spring-Boot-Starter-Parent 2.7.3" : 322
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-29 03:00:02.139106+09:00
카테고리는 java 로 하겠습니다.
주제는 How was there no collision among 50,000 random 7-digit hex strings? (The Birthday Problem) 로 하겠습니다.
제목 만들었습니다. Understanding the Absence of Collision in 50,000 Random 7-Digit Hex Strings: A Deep Dive into The Birthday Problem : 109
본문 1/2 만들었습니다. : 1219
본문 2/2 만들었습니다. : 1170
참고할만한 사이트를 만들었습니다. Understanding the Absence of Collision in 50,000 Random 7-Digit Hex Strings: A Deep Dive into The Birthday Problem : 391
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-01 17:00:01.527632+09:00
카테고리는 java 로 하겠습니다.
주제는 Is there a way to configure openapi-generator to use jakarta package during generation 로 하겠습니다.
제목 만들었습니다. "Configuring OpenAPI-Generator to Utilize Jakarta Package During Generation: A Solution to StackOverflow Errors" : 99
본문 1/2 만들었습니다. : 1236
본문 2/2 만들었습니다. : 1182
참고할만한 사이트를 만들었습니다. "Configuring OpenAPI-Generator to Utilize Jakarta Package During Generation: A Solution to StackOverflow Errors" : 300
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-07 19:00:01.506834+09:00
카테고리는 java 로 하겠습니다.
주제는 Seeded RandomGenerators in Java 17 로 하겠습니다.
제목 만들었습니다. Understanding and Fixing Seeded RandomGenerators Error in Java 17 : 84
본문 1/2 만들었습니다. : 1060
본문 2/2 만들었습니다. : 1112
참고할만한 사이트를 만들었습니다. Understanding and Fixing Seeded RandomGenerators Error in Java 17 : 365
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-08 15:00:02.178260+09:00
카테고리는 java 로 하겠습니다.
주제는 What is the explanation of null values in a cyclic dependency in final private enum fields? 로 하겠습니다.
제목 만들었습니다. Understanding Null Values in Cyclic Dependency of Final Private Enum Fields : 90
본문 1/2 만들었습니다. : 1344
본문 2/2 만들었습니다. : 1110
참고할만한 사이트를 만들었습니다. Understanding Null Values in Cyclic Dependency of Final Private Enum Fields : 340
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-08 21:00:02.274078+09:00
카테고리는 java 로 하겠습니다.
주제는 AdRequest &quot;This method should only be accessed from tests or within private scope&quot; 로 하겠습니다.
제목 만들었습니다. "Resolving the 'This Method Should Only Be Accessed from Tests or Within Private Scope' Error in AdRequest" : 103
본문 1/2 만들었습니다. : 1014
본문 2/2 만들었습니다. : 1093
참고할만한 사이트를 만들었습니다. "Resolving the 'This Method Should Only Be Accessed from Tests or Within Private Scope' Error in AdRequest" : 284
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-10 03:00:01.380373+09:00
카테고리는 java 로 하겠습니다.
주제는 jdk.internal.misc.Unsafe.park (Native method) crash in android app 로 하겠습니다.
제목 만들었습니다. "Resolving the jdk.internal.misc.Unsafe.park (Native Method) Crash in Android Apps" : 98
본문 1/2 만들었습니다. : 1228
본문 2/2 만들었습니다. : 995
참고할만한 사이트를 만들었습니다. "Resolving the jdk.internal.misc.Unsafe.park (Native Method) Crash in Android Apps" : 263
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-10 17:00:01.909862+09:00
카테고리는 java 로 하겠습니다.
주제는 upgrade to SnakeYaml 1.31 in spring-boot-starter-parent 2.7.3 로 하겠습니다.
제목 만들었습니다. "Resolving Error through Upgrading to SnakeYaml 1.31 in Spring-Boot-Starter-Parent 2.7.3" : 112
본문 1/2 만들었습니다. : 1339
본문 2/2 만들었습니다. : 1090
참고할만한 사이트를 만들었습니다. "Resolving Error through Upgrading to SnakeYaml 1.31 in Spring-Boot-Starter-Parent 2.7.3" : 411
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-12 17:00:01.402725+09:00
카테고리는 java 로 하겠습니다.
주제는 Is there a way to configure openapi-generator to use jakarta package during generation 로 하겠습니다.
제목 만들었습니다. "Configuring OpenAPI-Generator to Utilize Jakarta Package During Generation: A Solution to StackOverflow Errors" : 99
본문 1/2 만들었습니다. : 1424
본문 2/2 만들었습니다. : 960
참고할만한 사이트를 만들었습니다. "Configuring OpenAPI-Generator to Utilize Jakarta Package During Generation: A Solution to StackOverflow Errors" : 313
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-12 19:00:02.284649+09:00
카테고리는 java 로 하겠습니다.
주제는 How to configure kapt to generate Java17 Java stubs in Android Gradle build file 로 하겠습니다.
제목 만들었습니다. "Configuring Kapt to Generate Java17 Java Stubs in Android Gradle Build File: A Solution to StackOverflow's Common Error" : 107
본문 1/2 만들었습니다. : 1105
본문 2/2 만들었습니다. : 1109
참고할만한 사이트를 만들었습니다. "Configuring Kapt to Generate Java17 Java Stubs in Android Gradle Build File: A Solution to StackOverflow's Common Error" : 295
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-14 09:00:01.968589+09:00
카테고리는 java 로 하겠습니다.
주제는 Stream.peek() can be skipped for optimization 로 하겠습니다.
제목 만들었습니다. Optimizing Stream.peek() Usage in Java : 78
본문 1/2 만들었습니다. : 1069
본문 2/2 만들었습니다. : 764
참고할만한 사이트를 만들었습니다. Optimizing Stream.peek() Usage in Java : 486
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-15 13:00:02.187536+09:00
카테고리는 java 로 하겠습니다.
주제는 What is overhead of Java Native Memory Tracking in &quot;summary&quot; mode? 로 하겠습니다.
제목 만들었습니다. Understanding the Overhead of Java Native Memory Tracking in Summary Mode : 90
본문 1/2 만들었습니다. : 1230
본문 2/2 만들었습니다. : 904
참고할만한 사이트를 만들었습니다. Understanding the Overhead of Java Native Memory Tracking in Summary Mode : 345
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-16 09:00:01.664554+09:00
카테고리는 java 로 하겠습니다.
주제는 How can I run JDK 19 with Structured Concurrency? 로 하겠습니다.
제목 만들었습니다. "Implementing Structured Concurrency with JDK 19: A Comprehensive Guide" : 90
본문 1/2 만들었습니다. : 842
본문 2/2 만들었습니다. : 995
참고할만한 사이트를 만들었습니다. "Implementing Structured Concurrency with JDK 19: A Comprehensive Guide" : 313
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-16 19:00:01.824871+09:00
카테고리는 java 로 하겠습니다.
주제는 What is overhead of Java Native Memory Tracking in &quot;summary&quot; mode? 로 하겠습니다.
제목 만들었습니다. Understanding the Overhead of Java Native Memory Tracking in Summary Mode : 90
본문 1/2 만들었습니다. : 1086
본문 2/2 만들었습니다. : 982
참고할만한 사이트를 만들었습니다. Understanding the Overhead of Java Native Memory Tracking in Summary Mode : 312
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-17 21:00:01.848343+09:00
카테고리는 java 로 하겠습니다.
주제는 Post Spring Boot 3 update - Unable to instantiate factory class [org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver] 로 하겠습니다.
제목 만들었습니다. "Resolving Spring Boot 3 Update Error: Issues with Instantiating Factory Class [org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver]" : 115
본문 1/2 만들었습니다. : 1281
본문 2/2 만들었습니다. : 1035
참고할만한 사이트를 만들었습니다. "Resolving Spring Boot 3 Update Error: Issues with Instantiating Factory Class [org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver]" : 335
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-17 23:00:02.039152+09:00
카테고리는 java 로 하겠습니다.
주제는 Why does String creation using `newInstance()` method behave different when using `var` compared to using explicit type `String`? 로 하겠습니다.
제목 만들었습니다. Understanding the Difference in String Creation Using `newInstance()` Method: `var` vs Explicit Type `String` : 107
본문 1/2 만들었습니다. : 1054
본문 2/2 만들었습니다. : 946
참고할만한 사이트를 만들었습니다. Understanding the Difference in String Creation Using `newInstance()` Method: `var` vs Explicit Type `String` : 330
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-07-18 15:00:02.030736+09:00
카테고리는 java 로 하겠습니다.
StackAPI 오류발생 :  list index out of range
프로그램 종료.
